nodes:
  13:
    x: 0.2
    y: 0.8
    forward: []
    right_turn: []
    left_turn:
    - 31
    u_turn: []
  14:
    x: 0.2
    y: 1.6
    forward:
    - 13
    right_turn: []
    left_turn: []
    u_turn:
    - 24
  17:
    x: 0.2
    y: 2.4
    forward:
    - 14
    right_turn: []
    left_turn:
    - 35
    u_turn: []
  18:
    x: 0.2
    y: 3.2
    forward:
    - 17
    right_turn: []
    left_turn: []
    u_turn:
    - 28
  23:
    x: 0.6
    y: 0.8
    forward:
    - 24
    right_turn: []
    left_turn: []
    u_turn:
    - 13
  24:
    x: 0.6
    y: 1.6
    forward:
    - 27
    right_turn:
    - 35
    left_turn: []
    u_turn: []
  27:
    x: 0.6
    y: 2.4
    forward:
    - 28
    right_turn: []
    left_turn: []
    u_turn:
    - 17
  28:
    x: 0.6
    y: 3.2
    forward: []
    right_turn:
    - 39
    left_turn: []
    u_turn: []
  31:
    x: 0.8
    y: 0.2
    forward:
    - 41
    right_turn: []
    left_turn: []
    u_turn:
    - 32
  32:
    x: 0.8
    y: 0.6
    forward: []
    right_turn:
    - 23
    left_turn: []
    u_turn: []
  35:
    x: 0.8
    y: 1.8
    forward:
    - 45
    right_turn: []
    left_turn: []
    u_turn:
    - 36
  36:
    x: 0.8
    y: 2.2
    forward: []
    right_turn:
    - 27
    left_turn:
    - 14
    u_turn: []
  39:
    x: 0.8
    y: 3.4
    forward:
    - 49
    right_turn: []
    left_turn: []
    u_turn:
    - 310
  310:
    x: 0.8
    y: 3.8
    forward: []
    right_turn: []
    left_turn:
    - 18
    u_turn: []
  41:
    x: 1.6
    y: 0.2
    forward:
    - 71
    right_turn: []
    left_turn:
    - 63
    u_turn: []
  42:
    x: 1.6
    y: 0.6
    forward:
    - 32
    right_turn: []
    left_turn: []
    u_turn:
    - 41
  45:
    x: 1.6
    y: 1.8
    forward:
    - 75
    right_turn:
    - 54
    left_turn:
    - 67
    u_turn: []
  46:
    x: 1.6
    y: 2.2
    forward:
    - 36
    right_turn: []
    left_turn: []
    u_turn:
    - 45
  49:
    x: 1.6
    y: 3.4
    forward:
    - 79
    right_turn:
    - 58
    left_turn: []
    u_turn: []
  410:
    x: 1.6
    y: 3.8
    forward:
    - 310
    right_turn: []
    left_turn: []
    u_turn:
    - 49
  53:
    x: 1.8
    y: 0.8
    forward: []
    right_turn:
    - 42
    left_turn:
    - 71
    u_turn: []
  54:
    x: 1.8
    y: 1.6
    forward:
    - 53
    right_turn: []
    left_turn: []
    u_turn:
    - 64
  57:
    x: 1.8
    y: 2.4
    forward:
    - 54
    right_turn:
    - 46
    left_turn:
    - 75
    u_turn: []
  58:
    x: 1.8
    y: 3.2
    forward:
    - 57
    right_turn: []
    left_turn: []
    u_turn:
    - 68
  63:
    x: 2.2
    y: 0.8
    forward:
    - 64
    right_turn: []
    left_turn: []
    u_turn:
    - 53
  64:
    x: 2.2
    y: 1.6
    forward:
    - 67
    right_turn:
    - 75
    left_turn:
    - 46
    u_turn: []
  67:
    x: 2.2
    y: 2.4
    forward:
    - 68
    right_turn: []
    left_turn: []
    u_turn:
    - 57
  68:
    x: 2.2
    y: 3.2
    forward: []
    right_turn:
    - 79
    left_turn:
    - 410
    u_turn: []
  71:
    x: 2.4
    y: 0.2
    forward:
    - 81
    right_turn: []
    left_turn: []
    u_turn:
    - 72
  72:
    x: 2.4
    y: 0.6
    forward:
    - 42
    right_turn:
    - 63
    left_turn: []
    u_turn: []
  75:
    x: 2.4
    y: 1.8
    forward:
    - 85
    right_turn: []
    left_turn: []
    u_turn:
    - 76
  76:
    x: 2.4
    y: 2.2
    forward:
    - 46
    right_turn:
    - 67
    left_turn:
    - 54
    u_turn: []
  79:
    x: 2.4
    y: 3.4
    forward:
    - 89
    right_turn: []
    left_turn: []
    u_turn:
    - 710
  710:
    x: 2.4
    y: 3.8
    forward:
    - 410
    right_turn: []
    left_turn:
    - 58
    u_turn: []
  81:
    x: 3.2
    y: 0.2
    forward: []
    right_turn: []
    left_turn:
    - 103
    u_turn: []
  82:
    x: 3.2
    y: 0.6
    forward:
    - 72
    right_turn: []
    left_turn: []
    u_turn:
    - 81
  85:
    x: 3.2
    y: 1.8
    forward: []
    right_turn:
    - 94
    left_turn:
    - 107
    u_turn: []
  86:
    x: 3.2
    y: 2.2
    forward:
    - 76
    right_turn: []
    left_turn: []
    u_turn:
    - 85
  89:
    x: 3.2
    y: 3.4
    forward: []
    right_turn:
    - 98
    left_turn: []
    u_turn: []
  810:
    x: 3.2
    y: 3.8
    forward:
    - 710
    right_turn: []
    left_turn: []
    u_turn:
    - 89
  93:
    x: 3.4
    y: 0.8
    forward: []
    right_turn:
    - 82
    left_turn: []
    u_turn: []
  94:
    x: 3.4
    y: 1.6
    forward:
    - 93
    right_turn: []
    left_turn: []
    u_turn:
    - 104
  97:
    x: 3.4
    y: 2.4
    forward:
    - 94
    right_turn:
    - 86
    left_turn: []
    u_turn: []
  98:
    x: 3.4
    y: 3.2
    forward:
    - 97
    right_turn: []
    left_turn: []
    u_turn:
    - 108
  103:
    x: 3.8
    y: 0.8
    forward:
    - 104
    right_turn: []
    left_turn: []
    u_turn:
    - 93
  104:
    x: 3.8
    y: 1.6
    forward:
    - 107
    right_turn: []
    left_turn:
    - 86
    u_turn: []
  107:
    x: 3.8
    y: 2.4
    forward:
    - 108
    right_turn: []
    left_turn: []
    u_turn:
    - 97
  108:
    x: 3.8
    y: 3.2
    forward: []
    right_turn: []
    left_turn:
    - 810
    u_turn: []
start_node: 13
target_node: 108
initial_heading: 0.0
